# Configuration file with default values

batchsize: 64           # Batch size
zscore_method: "auc"    # Z-score method (zscore/robustz)
epoch: 20              # Training epochs
lr: 0.001               # Learning rate
wd: 0.001               # Weight decay
alpha: 0.3              # Loss parameter alpha
genotype_hiddens: 4     # Neurons in each term in genotype parts
patience: 30            # Early stopping epoch limit
delta: 0.001            # Minimum change in loss for improvement
min_dropout_layer: 2    # Start dropout from this layer
dropout_fraction: 0.3   # Dropout fraction
cuda: 0                 # Specify GPU
optimize: 1             # Hyper-parameter optimization (not implemented yet)
training_data: "./examples/training_data.txt"
predict_data: "./examples/test_data.txt"
gene2id: "./examples/gene2ind.txt"
cell2id: "./examples/cell2ind.txt"
mutations: "./examples/cell2mutation.txt"
cn_deletions: "./examples/cell2cndeletion.txt"
cn_amplifications: "./examples/cell2cnamplification.txt"
